package com.example.pdfsummarizer.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class PdfGeneratorService {

    private static final Logger logger = LoggerFactory.getLogger(PdfGeneratorService.class);

    public File generateSummaryPdf(String summaryText, String originalFilename, File outputDir) throws IOException, DocumentException {
        logger.debug("Generating summary PDF for original file: {}", originalFilename);

        // Ensure output directory exists
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }

        // Generate output filename
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String baseFilename = originalFilename.replaceAll("\\.[^.]+$", ""); // Remove extension
        String outputFilename = String.format("%s_summary_%s.pdf", baseFilename, timestamp);
        File outputFile = new File(outputDir, outputFilename);

        // Create PDF document
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(outputFile));

        document.open();

        try {
            // Add title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
            Paragraph title = new Paragraph("Document Summary", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Add metadata
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
            Paragraph meta = new Paragraph();
            meta.add(new Chunk("Original Document: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.GRAY)));
            meta.add(new Chunk(originalFilename, metaFont));
            meta.add(Chunk.NEWLINE);
            meta.add(new Chunk("Summary Generated: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.GRAY)));
            meta.add(new Chunk(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), metaFont));
            meta.setSpacingAfter(30);
            document.add(meta);

            // Add separator line
            Paragraph separator = new Paragraph("_".repeat(80));
            separator.setAlignment(Element.ALIGN_CENTER);
            separator.setSpacingAfter(20);
            document.add(separator);

            // Add summary content
            Font contentFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);
            
            // Split summary into paragraphs for better formatting
            String[] paragraphs = summaryText.split("\n\n");
            for (String paragraphText : paragraphs) {
                if (!paragraphText.trim().isEmpty()) {
                    Paragraph paragraph = new Paragraph(paragraphText.trim(), contentFont);
                    paragraph.setAlignment(Element.ALIGN_JUSTIFIED);
                    paragraph.setSpacingAfter(15);
                    paragraph.setFirstLineIndent(20);
                    document.add(paragraph);
                }
            }

            // Add footer
            document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("_".repeat(80));
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(30);
            document.add(footer);

            Paragraph footerText = new Paragraph("Generated by PDF Summarizer Application", metaFont);
            footerText.setAlignment(Element.ALIGN_CENTER);
            footerText.setSpacingBefore(10);
            document.add(footerText);

        } finally {
            document.close();
        }

        logger.debug("Successfully generated summary PDF: {}", outputFile.getAbsolutePath());
        return outputFile;
    }

    public File generateDetailedSummaryPdf(String summaryText, String originalFilename, 
                                         File outputDir, int originalPageCount, 
                                         int originalWordCount) throws IOException, DocumentException {
        logger.debug("Generating detailed summary PDF for original file: {}", originalFilename);

        // Ensure output directory exists
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }

        // Generate output filename
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String baseFilename = originalFilename.replaceAll("\\.[^.]+$", ""); // Remove extension
        String outputFilename = String.format("%s_detailed_summary_%s.pdf", baseFilename, timestamp);
        File outputFile = new File(outputDir, outputFilename);

        // Create PDF document
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(outputFile));

        document.open();

        try {
            // Add title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.DARK_GRAY);
            Paragraph title = new Paragraph("Detailed Document Summary", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(30);
            document.add(title);

            // Add document information section
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
            Paragraph docInfoTitle = new Paragraph("Document Information", sectionFont);
            docInfoTitle.setSpacingAfter(15);
            document.add(docInfoTitle);

            Font infoFont = FontFactory.getFont(FontFactory.HELVETICA, 11, BaseColor.BLACK);
            Paragraph docInfo = new Paragraph();
            docInfo.add(new Chunk("• Original Document: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            docInfo.add(new Chunk(originalFilename, infoFont));
            docInfo.add(Chunk.NEWLINE);
            docInfo.add(new Chunk("• Page Count: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            docInfo.add(new Chunk(String.valueOf(originalPageCount), infoFont));
            docInfo.add(Chunk.NEWLINE);
            docInfo.add(new Chunk("• Estimated Word Count: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            docInfo.add(new Chunk(String.valueOf(originalWordCount), infoFont));
            docInfo.add(Chunk.NEWLINE);
            docInfo.add(new Chunk("• Summary Generated: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            docInfo.add(new Chunk(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), infoFont));
            docInfo.setSpacingAfter(25);
            document.add(docInfo);

            // Add summary section
            Paragraph summaryTitle = new Paragraph("Executive Summary", sectionFont);
            summaryTitle.setSpacingAfter(15);
            document.add(summaryTitle);

            // Add summary content
            Font contentFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);
            
            String[] paragraphs = summaryText.split("\n\n");
            for (String paragraphText : paragraphs) {
                if (!paragraphText.trim().isEmpty()) {
                    Paragraph paragraph = new Paragraph(paragraphText.trim(), contentFont);
                    paragraph.setAlignment(Element.ALIGN_JUSTIFIED);
                    paragraph.setSpacingAfter(15);
                    paragraph.setFirstLineIndent(20);
                    document.add(paragraph);
                }
            }

            // Add statistics section
            document.add(Chunk.NEWLINE);
            Paragraph statsTitle = new Paragraph("Summary Statistics", sectionFont);
            statsTitle.setSpacingAfter(15);
            document.add(statsTitle);

            int summaryWordCount = summaryText.split("\\s+").length;
            double compressionRatio = originalWordCount > 0 ? (double) summaryWordCount / originalWordCount : 0;

            Paragraph stats = new Paragraph();
            stats.add(new Chunk("• Summary Word Count: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            stats.add(new Chunk(String.valueOf(summaryWordCount), infoFont));
            stats.add(Chunk.NEWLINE);
            stats.add(new Chunk("• Compression Ratio: ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.BLACK)));
            stats.add(new Chunk(String.format("%.1f%% (%.2fx reduction)", compressionRatio * 100, 1/compressionRatio), infoFont));
            stats.setSpacingAfter(30);
            document.add(stats);

            // Add footer
            Paragraph footer = new Paragraph("_".repeat(80));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9, BaseColor.GRAY);
            Paragraph footerText = new Paragraph("Generated by PDF Summarizer Application", footerFont);
            footerText.setAlignment(Element.ALIGN_CENTER);
            footerText.setSpacingBefore(10);
            document.add(footerText);

        } finally {
            document.close();
        }

        logger.debug("Successfully generated detailed summary PDF: {}", outputFile.getAbsolutePath());
        return outputFile;
    }
}